"""Milvus vector store client — collection management and hybrid search."""

from __future__ import annotations

from typing import Any
import json

from pymilvus import (
    MilvusClient,
    DataType,
    Function,
    FunctionType,
    AnnSearchRequest,
    RRFRanker,
)

from src.config import get_settings


class MilvusStore:
    """Wraps PyMilvusClient for collection management + hybrid search."""

    COLLECTION_NAME: str = "doc_chunks"
    _DEFAULT_DIM: int = 1024  # Qwen3-Embedding-0.6B output dim

    def __init__(self, uri: str, token: str | None = None) -> None:
        self._uri = uri
        self._token = token
        self.client = MilvusClient(uri=uri, token=token or "")

    def close(self) -> None:
        try:
            self.client.close()
        except Exception:
            pass

    # ── Collection Management ──────────────────────────────────────

    def ensure_collection(self, dim: int | None = None) -> None:
        """Idempotent: create collection + indexes if not exists."""
        dim = dim or self._DEFAULT_DIM

        if self.client.has_collection(self.COLLECTION_NAME):
            self.client.load_collection(self.COLLECTION_NAME)
            return

        schema = self.client.create_schema(auto_id=False, enable_dynamic_field=False)

        # Primary key
        schema.add_field("chunk_id", DataType.VARCHAR, max_length=64, is_primary=True)
        # Foreign key into Redis parent store
        schema.add_field("parent_id", DataType.VARCHAR, max_length=64)
        schema.add_field("doc_id", DataType.VARCHAR, max_length=64)
        # Full text (analyzed for BM25)
        schema.add_field(
            "text",
            DataType.VARCHAR,
            max_length=4096,
            enable_analyzer=True,
            analyzer_params={"type": "chinese"},
        )
        # Sparse vector auto-generated by BM25 function
        schema.add_field("sparse_vector", DataType.SPARSE_FLOAT_VECTOR)
        # Dense vector from local Qwen3-Embedding
        schema.add_field("dense_vector", DataType.FLOAT_VECTOR, dim=dim)
        # Metadata
        schema.add_field("title_path", DataType.VARCHAR, max_length=512)
        schema.add_field("source", DataType.VARCHAR, max_length=256)
        schema.add_field("chunk_type", DataType.VARCHAR, max_length=16)
        schema.add_field("page", DataType.INT32)
        schema.add_field("chunk_index", DataType.INT32)

        # BM25 function: auto-generates sparse_vector from text
        bm25_fn = Function(
            name="bm25",
            input_field_names=["text"],
            output_field_names=["sparse_vector"],
            function_type=FunctionType.BM25,
        )
        schema.add_function(bm25_fn)

        # Index params
        index_params = self.client.prepare_index_params()

        # Dense vector: HNSW
        index_params.add_index(
            field_name="dense_vector",
            index_type="HNSW",
            metric_type="COSINE",
            params={"M": 16, "efConstruction": 200},
        )
        # Sparse vector: inverted index for BM25
        index_params.add_index(
            field_name="sparse_vector",
            index_type="SPARSE_INVERTED_INDEX",
            metric_type="BM25",
        )
        # Scalar indexes for filtering
        index_params.add_index(field_name="doc_id", index_type="TRIE")
        index_params.add_index(field_name="parent_id", index_type="TRIE")

        self.client.create_collection(
            collection_name=self.COLLECTION_NAME,
            schema=schema,
            index_params=index_params,
        )
        self.client.load_collection(self.COLLECTION_NAME)

    # ── Data Operations ────────────────────────────────────────────

    def insert_batch(self, data: list[dict[str, Any]], batch_size: int = 100) -> int:
        """Insert chunks in batches. Returns total inserted count."""
        total = 0
        for i in range(0, len(data), batch_size):
            batch = data[i : i + batch_size]
            result = self.client.insert(collection_name=self.COLLECTION_NAME, data=batch)
            total += result.get("insert_count", len(batch))
        return total

    def delete_by_doc_id(self, doc_id: str) -> None:
        """Remove all chunks belonging to a document."""
        self.client.delete(
            collection_name=self.COLLECTION_NAME,
            filter=f'doc_id == "{doc_id}"',
        )

    # ── Hybrid Search ──────────────────────────────────────────────

    def hybrid_search(
        self,
        query_embedding: list[float],
        query_text: str,
        *,
        top_k: int = 8,
        dense_limit: int = 20,
        sparse_limit: int = 20,
        rrf_k: int = 60,
        filter_expr: str | None = None,
    ) -> list[dict[str, Any]]:
        """
        Dense (COSINE) + Sparse (BM25) hybrid search with RRF fusion.
        """
        dense_req = AnnSearchRequest(
            data=[query_embedding],
            anns_field="dense_vector",
            param={"metric_type": "COSINE", "params": {"ef": 64}},
            limit=dense_limit,
            expr=filter_expr,
        )
        sparse_req = AnnSearchRequest(
            data=[query_text],
            anns_field="sparse_vector",
            param={"metric_type": "BM25"},
            limit=sparse_limit,
            expr=filter_expr,
        )

        results = self.client.hybrid_search(
            collection_name=self.COLLECTION_NAME,
            reqs=[dense_req, sparse_req],
            ranker=RRFRanker(k=rrf_k),
            limit=top_k,
            output_fields=[
                "parent_id", "text", "title_path",
                "source", "page", "chunk_index", "chunk_type",
            ],
        )
        return results[0] if results else []

    def build_filter_expr(self, filters: dict[str, Any] | None) -> str | None:
        """Convert dict filters to Milvus scalar expression."""
        if not filters:
            return None
        parts = []
        for key, value in filters.items():
            if isinstance(value, str):
                parts.append(f'{key} == "{value}"')
            elif isinstance(value, int):
                parts.append(f"{key} == {value}")
        return " and ".join(parts) if parts else None
